name: check-streams

permissions:
  contents: write

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Run checker
        run: python check.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add status.json
          git commit -m "update status" || exit 0
          git push
